# -*- coding: utf-8 -*-
"""English page content for Jev Hub."""

from datetime import date

CRUMB_HOME = [("Home", "/")]

import json as _json

# ---------------------------------------------------------------- shared data

NEWS = [
    ("2026-09-21", "Jev opens up: no waitlist, $5 free credit for every signup",
     "TypeSafe removed the waitlist entirely — console.typesafe.ai is now open registration, with $5 in free credit (~120M input tokens) for new users. The Vercel and Cloudflare gateway paths continue unchanged.",
     "console.typesafe.ai / aicrier"),
    ("2026-09-18", "Independent analyses urge caution on Jev benchmarks",
     "Multiple third-party write-ups (The Tech Society, DataCamp, dev.to) compile Jev's numbers and flag that the 4-workflow benchmark is vendor-run, with consensus labels generated by GPT-6 Astra and Claude Fable 5.1 rather than ground truth. Accuracy on your own traffic remains the recommended test.",
     "digitalstrategy-ai.com"),
    ("2026-09-17", "TypeSafe clears 140,000 users off the waitlist in 36 hours",
     "After launch-day demand, TypeSafe reported moving 140k signups off the waitlist within roughly a day and a half, while asking new users to keep using the Vercel AI Gateway in the meantime. Production reports cited include a -71% cost and -90% wall-time reduction on a dispatch workflow, and 1,018 research papers classified for $0.08 at 256ms median latency.",
     "marketbrief.now"),
    ("2026-09-16", "Jev lands on Vercel AI Gateway",
     "Vercel CEO Rauch Grover confirmed Jev is available through the Vercel AI Gateway under typesafe-ai/jev, reporting up to 18x faster p95 responses versus text-generating models on routing workloads. This becomes the fastest no-waitlist path to a Jev API key.",
     "vercel.com / x.com"),
    ("2026-09-16", "Cloudflare, OpenRouter and LangChain add Jev on day one",
     "Cloudflare Workers AI lists typesafe/jev (32K context), OpenRouter lists typesafe/jev-1.13 (64K context, $0.042/1M input, $0 output), and LangChain publishes a guide for building evaluation harnesses with Jev via the langchain-typesafe package.",
     "openrouter.ai"),
    ("2026-09-15", "Launch: TypeSafe introduces System One Models and Jev",
     "TypeSafe AI launches Jev, a model that returns typed decisions (Choice, Score, Noul) with calibrated probabilities instead of generating text. Headline claims: 193.6x faster and 444.6x cheaper than frontier LLMs on System One workflows, $0.042 per 1M input tokens with output unmetered, and 0% schema/type errors by construction.",
     "typesafe.ai"),
]

PROJECTS = [
    ("openjev", "Open-source reproduction of the Jev interface pattern on a small open model, reading typed option probabilities off the logits. Community proof that the primitive outlives any single vendor.", "github.com/community"),
    ("jev-ultrafast (Browser Use)", "Browser agent using Jev as its decision layer. Demo: Zürich→London Google Flights search completed in 7.1 seconds.", "browser-use"),
    ("mobile-jev (Droidrun)", "Phone agent driving Uber on a real Android device: 9 actions in about 21 seconds (no booking completed).", "droidrun"),
    ("jev-guard", "Agent guardrail that rates every tool call as deny / ask / allow before execution.", "community"),
    ("pg-jev", "Adds plain-language filtering to Postgres queries via Jev decisions.", "community"),
    ("HA-Jev", "Turns Jev answers into Home Assistant entities for smart-home logic.", "community"),
    ("jevmeter", "Scores every sentence of a video debate for about $0.05 total.", "community"),
    ("jev-trader", "Market signal experiments. Note: independent testing shows Jev performs no better than a coin flip on short-horizon price prediction — classification, not prediction.", "community"),
    ("typesafe-computer-use", "Computer-use agent with Jev as the cheap gatekeeper for every action.", "community"),
    ("Typewriter (Steve Krouse)", "Live typing demo that updates 16 Jev judgments in real time as you type.", "community"),
    ("heist-one", "Game demo where Jev runs the guard AI logic.", "community"),
]

FAQS = [
    ("basics", "What is Jev in one sentence?",
     "Jev is a \"System One\" AI model by TypeSafe that reads your input (state) plus typed questions and returns choices, scores, or true/false probabilities with confidence estimates — it never generates free-form text."),
    ("basics", "What are Jev's three question primitives?",
     "<strong>Choice</strong> (pick one option from a list you define), <strong>Score</strong> (an ordinal rating such as low/medium/high/critical), and <strong>Noul</strong> (TypeSafe's binary type: the probability that a statement is true, e.g. 0.95). Multiple questions can share one request."),
    ("basics", "Why is it called a \"System One\" model?",
     "A reference to Kahneman's Thinking, Fast and Slow: System 1 is fast, instinctive judgment. Jev handles the fast, bounded judgment calls (routing, scoring, approving) so that slow \"System 2\" reasoning — frontier LLMs or humans — is spent only where it matters."),
    ("basics", "Is Jev a replacement for ChatGPT or Claude?",
     "No. Jev cannot write text, draft emails, summarize, or reason openly. It is a complement: it takes over the structured decision steps of an LLM stack so the expensive generative model is called less often."),
    ("access", "Do I have to wait on the TypeSafe waitlist?",
     "No — as of Sep 20, 2026 the waitlist is gone. Jev is open to everyone: sign up at console.typesafe.ai and get $5 in free credit (~120M tokens). The Vercel AI Gateway (typesafe-ai/jev) and Cloudflare Workers AI (typesafe/jev) also serve it directly."),
    ("access", "Is there a free playground?",
     "Yes. Approved users get console.typesafe.ai/playground: paste text as state, write a plain-language question, pick the answer type, and get a sub-second result with a confidence score. You can mix Choice, Score, and Noul questions in one run."),
    ("access", "Which SDKs are available?",
     "Official Python and JavaScript/TypeScript SDKs ship from TypeSafe, plus framework integrations: the Vercel AI SDK (via @ai-sdk/typesafe) and LangChain (langchain-typesafe package)."),
    ("access", "What are the rate limits?",
     "Early-access defaults are reported at roughly 250,000 tokens per second and 1,200 requests per minute, with higher tiers available under enterprise agreements. Treat these as launch figures that may change."),
    ("pricing", "How much does Jev cost?",
     "The reference price is $0.042 per 1 million input tokens ($42 per billion), with output tokens unmetered and free — because the model returns structured decisions, not long text. A typical typed decision costs on the order of $0.0001 or less depending on state length."),
    ("pricing", "Is Jev's output really free?",
     "Yes. Output is billed at $0 across all listed providers. The output is a compact typed decision (an option, a score, a probability), not a stream of generated tokens."),
    ("pricing", "How does Jev's price compare to LLMs?",
     "TypeSafe claims the $0.042/1M input rate is roughly 238x lower than \"Claude Fable 5.1\" and about 1/48th of GPT-5.6 Terra's $2.00/1M input — and those models also bill $2–$12 per 1M output tokens, which Jev doesn't charge at all. See our pricing page for a full comparison table."),
    ("pricing", "Can the aggressive pricing change?",
     "Yes — and TypeSafe itself is candid about it: it cannot prove the price isn't subsidized and expects prices to fall rather than rise, but the current rate is a launch figure, not a guarantee. Our news page tracks price changes automatically."),
    ("technical", "What can Jev NOT do?",
     "It cannot generate text or explanations, cannot process images or audio (text only), cannot do arithmetic or date math (do that in code), and has a 64,000-token context window (32,000 on Cloudflare). It is also sensitive to irrelevant context — strip noise from the state before sending."),
    ("technical", "Is Jev really hallucination-free?",
     "Precisely: it cannot produce text hallucinations because it never generates text, and its schema guarantee means it can only return one of the options you defined (0% type/structured-output errors by construction). But a valid answer can still be a wrong answer with high confidence attached — calibrate thresholds on your own data before automating."),
    ("technical", "What does the API look like?",
     "A single HTTP call to the System One endpoint (e.g. POST https://api.typesafe.ai/v1/systemone with model jev-latest) carrying a state string and a map of typed questions; the response returns each answer with its probability. See our Get Access page for a copy-paste quickstart."),
    ("technical", "How fast is Jev?",
     "Reported end-to-end response times run 70–500ms, with community benchmarks around 200–260ms median per decision. TypeSafe's headline claim is 193.6x faster than text-generating models on System One workflows."),
    ("trust", "Are Jev's benchmark numbers reliable?",
     "Treat them as promising but unproven. The 4-workflow benchmark (67.8% accuracy at $0.0004/case) was designed and run by TypeSafe, scored against consensus labels from GPT-6 Astra and Claude Fable 5.1 rather than ground truth — which TypeSafe itself admits biases toward OpenAI and Anthropic. No independent neutral-harness reproduction has surfaced yet."),
    ("trust", "What is openjev?",
     "An open-source community project that reproduces the Jev interface pattern on a small open model by reading typed option probabilities off the logits — evidence that the typed-decision primitive is durable even beyond one vendor."),
    ("trust", "Who is behind TypeSafe AI?",
     "TypeSafe AI is a startup that built Jev around a new training algorithm called Reinforcement Learning for Calibrated Decisions (RLCD). It entered the spotlight in September 2026 when 140,000+ people joined the waitlist within days of launch."),
    ("trust", "Where does Jev Hub get its information?",
     "From TypeSafe's official site and docs, provider listings (OpenRouter, Cloudflare, Vercel), Hacker News and Reddit discussions, and independent write-ups — each news item links to its source. We mark all vendor-reported figures as self-reported and update this site automatically as new information appears."),
]


def faq_html_and_schema():
    groups = {}
    for cat, q, a in FAQS:
        groups.setdefault(cat, []).append((q, a))
    titles = {"basics": "Basics", "access": "Access", "pricing": "Pricing", "technical": "Technical", "trust": "Trust & Sources"}
    html, n = [], 1
    schema_entities = []
    for cat, qs in groups.items():
        html.append(f'<h2 id="{cat}">{titles[cat]}</h2>')
        for q, a in qs:
            html.append(f'<details><summary>{q}</summary><div class="a">{a}</div></details>')
            schema_entities.append({"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a.replace("<strong>", "").replace("</strong>", "")}})
            n += 1
    schema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": schema_entities}
    return "\n".join(html), schema


def faq_teaser(idxs):
    """Render a small FAQ block (visible <details>) + matching FAQPage schema."""
    html, ents = [], []
    for i in idxs:
        _cat, q, a = FAQS[i]
        html.append(f'<details><summary>{q}</summary><div class="a">{a}</div></details>')
        ents.append({"@type": "Question", "name": q, "acceptedAnswer": {"@type": "Answer", "text": a.replace("<strong>", "").replace("</strong>", "")}})
    return "\n".join(html), {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": ents}


# ---------------------------------------------------------------- pages

PAGES = {}

# ---- index ----
PAGES["index"] = {
    "title": "Jev AI: Pricing, Access & News Tracker | Jev Hub",
    "desc": "Independent hub for Jev, TypeSafe AI's System One model: what it is, pricing across providers, benchmarks with caveats, open-access paths (now with free credit), and auto-updated news.",
    "crumb": [("Home", None)],
    "schema": [
        {"@context": "https://schema.org", "@type": "WebSite", "name": "Jev Hub", "url": "https://jev-ai.live/",
         "description": "Independent tracker for Jev, the System One model by TypeSafe AI.",
         "inLanguage": ["en", "zh"]},
        {"@context": "https://schema.org", "@type": "Organization", "name": "Jev Hub",
         "url": "https://jev-ai.live/", "logo": "https://jev-ai.live/og/en-index.png",
         "slogan": "Jev AI, decoded — pricing, access, benchmarks & news in one place"},
    ],
    "body": """
<div class="hero">
  <div class="eyebrow"><span class="dot"></span> SYSTEM ONE MODEL · BY TYPESAFE AI · 2026</div>
  <h1>Jev AI, <span class="accent">decoded</span>: pricing, access, benchmarks &amp; news.</h1>
  <p class="lede">Jev doesn't write text — it returns <strong>typed decisions with calibrated probabilities</strong>. It's open to everyone now: grab $5 in free credit at console.typesafe.ai, or judge it yourself right here — <strong>no signup, 5 free runs a day</strong>. This hub tracks what it is, what it costs, and how to build on it — and keeps answering as things change.</p>
  <div class="hero-cta">
    <a class="btn btn-primary" href="/playground/">Try it free — no signup</a>
  </div>
  <div class="stat-grid">
    <div class="stat"><div class="num">193.6x</div><div class="lbl">faster than frontier LLMs (self-reported)</div></div>
    <div class="stat"><div class="num">444.6x</div><div class="lbl">cheaper per workflow case (self-reported)</div></div>
    <div class="stat"><div class="num alt">$0.042</div><div class="lbl">per 1M input tokens — output free</div></div>
    <div class="stat"><div class="num warn">$5</div><div class="lbl">free credit — open access, no waitlist</div></div>
  </div>
</div>

<section>
  <div class="kicker">01 · What is Jev</div>
  <h2>Jev, in 30 seconds</h2>
  <p>Jev reads a block of text (the <strong>state</strong>) plus questions you define, and returns one of three typed answers — a <strong>Choice</strong> from your options, an ordinal <strong>Score</strong>, or a <strong>Noul</strong> true/false probability — each with a confidence estimate. Because the answer shape is fixed in advance, it can't invent text, and it runs 20–200x faster than chat models at 40–400x lower cost. Your code sets confidence thresholds: act automatically when Jev is sure, escalate to a human or a frontier LLM when it isn't.</p>
  <p><a href="/what-is-jev/">Read the full explainer →</a></p>
</section>

<section>
  <div class="kicker">02 · Latest news</div>
  <h2>Jev news, tracked daily</h2>
  <div class="timeline">
    {NEWS_PREVIEW}
  </div>
  <p><a href="/news/">See the full timeline →</a></p>
</section>

<section>
  <div class="kicker">03 · Access</div>
  <h2>Start using Jev today</h2>
  <p>Jev opened to everyone on Sep 20 — no waitlist. Sign up directly, or go through a gateway:</p>
  <div class="card-grid">
    <a class="card" href="/get-access/#console"><span class="tag">Open now</span><h2>TypeSafe Console</h2><p>console.typesafe.ai — free $5 credit (~120M tokens), playground and API keys included.</p></a>
    <a class="card" href="/get-access/#vercel"><span class="tag">Fastest</span><h2>Vercel AI Gateway</h2><p>typesafe-ai/jev — live since launch day, no separate signup if you're on Vercel.</p></a>
    <a class="card" href="/get-access/#cloudflare"><span class="tag">Edge</span><h2>Cloudflare Workers AI</h2><p>typesafe/jev — 32K context, runs at the edge, per-request billing.</p></a>
  </div>
</section>

<section>
  <div class="kicker">04 · Pricing</div>
  <h2>Pricing at a glance</h2>
  <div class="table-wrap">
    <table>
      <thead><tr><th></th><th>Jev</th><th>Typical chat LLM</th></tr></thead>
      <tbody>
        <tr><td><strong>Input</strong></td><td class="mono good">$0.042 / 1M tokens</td><td class="mono">$0.25 – $3.00 / 1M tokens</td></tr>
        <tr><td><strong>Output</strong></td><td class="mono good">$0 (free)</td><td class="mono">$2 – $15 / 1M tokens</td></tr>
        <tr><td><strong>Latency</strong></td><td class="mono good">70–500 ms</td><td class="mono">2 – 80 s</td></tr>
        <tr><td><strong>Returns</strong></td><td>Typed decision + confidence</td><td>Free-form text</td></tr>
      </tbody>
    </table>
  </div>
  <p><a href="/pricing/">Full provider comparison + cost calculator →</a></p>
</section>

<section>
  <div class="kicker">05 · Start here</div>
  <h2>Explore the hub</h2>
  <div class="card-grid">
    <a class="card" href="/what-is-jev/"><span class="tag">Guide</span><h2>What is Jev?</h2><p>System One models explained: primitives, architecture, benchmarks and honest limitations.</p></a>
    <a class="card" href="/use-cases/"><span class="tag">Playbook</span><h2>10 use cases</h2><p>Routing, triage, guardrails, RAG filtering — with real community numbers.</p></a>
    <a class="card" href="/vs-llm/"><span class="tag">Decision</span><h2>Jev vs LLMs</h2><p>When the cheap typed model wins, and when you still need a frontier LLM.</p></a>
    <a class="card" href="/ecosystem/"><span class="tag">Build</span><h2>Ecosystem</h2><p>openjev, jev-ultrafast, pg-jev and a dozen community projects building on Jev.</p></a>
    <a class="card" href="/faq/"><span class="tag">Answers</span><h2>FAQ</h2><p>20 questions answered: access, pricing, limits, and what to distrust.</p></a>
    <a class="card" href="/playground/"><span class="tag">Tool</span><h2>Playground</h2><p>Run real Jev decisions in your browser with your own API key — Choice, Score, Noul, live probabilities.</p></a>
    <a class="card" href="/zh/"><span class="tag">中文</span><h2>中文版</h2><p>本站的完整中文版本，内容同步更新。</p></a>
  </div>
</section>

<section>
  <div class="kicker">06 · FAQ</div>
  <h2>Jev AI FAQ — the short version</h2>
  {FAQ_TEASER}
  <p><a href="/faq/">All 20 questions, straight answers →</a></p>
</section>
""",
}

# ---- what-is-jev ----
PAGES["what-is-jev"] = {
    "title": "What Is Jev AI? TypeSafe's System One Model Explained (2026)",
    "desc": "A complete 2026 guide to Jev: how System One models work, the Choice/Score/Noul primitives, RLCD training, benchmarks with honest caveats, pricing, and limitations.",
    "crumb": CRUMB_HOME + [("What is Jev", None)],
    "schema": [{
        "@context": "https://schema.org", "@type": "Article",
        "headline": "What Is Jev? TypeSafe's System One Model Explained",
        "datePublished": "2026-09-20", "dateModified": date.today().isoformat(),
        "author": {"@type": "Organization", "name": "Jev Hub"},
        "publisher": {"@type": "Organization", "name": "Jev Hub"},
        "about": {"@type": "SoftwareApplication", "name": "Jev", "applicationCategory": "AI Model"},
    }],
    "body": """
<p class="updated">Last updated: 2026-09-20 · Sources: typesafe.ai, provider listings, independent write-ups (linked inline)</p>
<h1>What Is Jev AI? TypeSafe's System One Model Explained</h1>
<p class="lede">Jev is the first of a new model class — <strong>System One Models</strong> — announced by TypeSafe AI on September 15, 2026. Instead of generating text, it answers typed questions about your input and returns structured decisions with calibrated probabilities. This guide explains how it works, what it can and cannot do, and which claims you should verify yourself.</p>

<div class="toc"><div class="t">On this page</div>
<ol>
  <li><a href="#tldr">TL;DR</a></li>
  <li><a href="#problem">The problem with chat models</a></li>
  <li><a href="#how">How Jev works</a></li>
  <li><a href="#primitives">The three primitives</a></li>
  <li><a href="#benchmarks">Benchmarks — and their caveats</a></li>
  <li><a href="#pricing">Pricing in one table</a></li>
  <li><a href="#limits">Limitations</a></li>
  <li><a href="#mental">The right mental model</a></li>
  <li><a href="#access">How to try it</a></li>
</ol></div>

<h2 id="tldr">TL;DR</h2>
<ul>
  <li><strong>What:</strong> a model that returns typed decisions (a choice, a score, or a true/false probability) with confidence estimates — never free-form text.</li>
  <li><strong>Why it matters:</strong> ~193.6x faster and ~444.6x cheaper than frontier LLMs on structured-decision workflows (TypeSafe's own numbers), because there is no sequential token generation.</li>
  <li><strong>Price:</strong> $0.042 per 1M input tokens; output is free.</li>
  <li><strong>Status:</strong> generally available (since Sep 20, 2026) — $5 free credit at console.typesafe.ai, or via the Vercel / Cloudflare gateways.</li>
  <li><strong>Catch:</strong> benchmarks are vendor-run and not independently reproduced; a valid answer can still be wrong with high confidence.</li>
</ul>

<h2 id="problem">The problem with chat models</h2>
<p>RLHF-era LLMs are optimized to produce words people like. That makes them superhuman at instruction following — and unreliable as software components: they drop modes, express overconfidence, hallucinate free-form text, and wrap every answer in prose. If what your application actually needs is <em>“which of these 4 categories is this ticket?”</em> or <em>“is this claim supported by this source?”</em>, a chat model is an expensive, noisy way to get a one-bit answer.</p>
<p>TypeSafe's bet is that a large share of what people currently ask LLMs to do is <strong>structured decision-making dressed up as chat</strong> — and that this share deserves its own model class, natively consumed by machines.</p>

<h2 id="how">How Jev works</h2>
<h3>Input: state + typed questions</h3>
<p>You send one HTTP request containing a <strong>state</strong> (a block of text to judge — a ticket, a paragraph, a log line) and one or more <strong>questions</strong>, each with a fixed answer type. The response returns every answer with a probability, in a single pass.</p>
<pre><code>{
  <span class="c-key">"state"</span>: <span class="c-str">"Hi, I've been trying to connect my Stripe account
    for 3 days and it keeps failing. I'm losing sales."</span>,
  <span class="c-key">"questions"</span>: {
    <span class="c-key">"urgency"</span>:   { <span class="c-key">"type"</span>: <span class="c-str">"noul"</span>,   <span class="c-key">"statement"</span>: <span class="c-str">"This message expresses urgency."</span> },
    <span class="c-key">"category"</span>:  { <span class="c-key">"type"</span>: <span class="c-str">"choice"</span>, <span class="c-key">"options"</span>: [<span class="c-str">"billing"</span>, <span class="c-str">"technical"</span>, <span class="c-str">"sales"</span>, <span class="c-str">"spam"</span>] },
    <span class="c-key">"frustration"</span>:{ <span class="c-key">"type"</span>: <span class="c-str">"score"</span>,  <span class="c-key">"scale"</span>: [<span class="c-str">"low"</span>, <span class="c-str">"medium"</span>, <span class="c-str">"high"</span>, <span class="c-str">"critical"</span>] }
  }
}</code></pre>
<h3>Training: RLCD, not RLHF</h3>
<p>TypeSafe built Jev with a new architecture, a new sampler, and a training algorithm called <strong>Reinforcement Learning for Calibrated Decisions (RLCD)</strong>. The optimization target is calibration — a 0.9 should actually mean 90% — rather than human preference on generated prose. This is also why the model cannot produce invalid answers: the output shape is fixed at the architecture level, not by prompt engineering.</p>
<h3>Output: decisions + confidence thresholds</h3>
<p>Your code owns the policy: auto-execute above 0.9, escalate to a human between 0.6 and 0.9, fall back to a frontier LLM below that. TypeSafe's framing: <em>“Combine those decisions in code to build larger workflows, with control over how the intelligence is used.”</em></p>

<h2 id="primitives">The three primitives</h2>
<div class="table-wrap">
<table>
  <thead><tr><th>Primitive</th><th>Returns</th><th>Example question</th></tr></thead>
  <tbody>
    <tr><td><strong>Choice</strong></td><td>One option from your list + probability</td><td>“Which category is this ticket?” → billing (0.91)</td></tr>
    <tr><td><strong>Score</strong></td><td>An ordinal rating + probability</td><td>“How severe is this alert?” → high (0.87)</td></tr>
    <tr><td><strong>Noul</strong></td><td>True/false probability for a statement</td><td>“Does this paragraph deny the claim it cites?” → 0.95</td></tr>
  </tbody>
</table>
</div>
<p>All three can share one request — a common pattern is fanning out every question you might need (speculative fan-out) and letting code pick the relevant answers, because adding questions barely moves the bill when input is the only thing priced.</p>

<h2 id="benchmarks">Benchmarks — and their caveats</h2>
<p>TypeSafe ran a custom 4-workflow evaluation (security incident response, agent-trace observability, invoice processing, customer service):</p>
<div class="table-wrap">
<table>
  <thead><tr><th>Model</th><th>Accuracy*</th><th>Cost / case</th><th>Latency</th></tr></thead>
  <tbody>
    <tr><td><strong>Jev</strong></td><td class="mono">67.8%</td><td class="mono good">$0.0004</td><td class="mono good">0.4 s</td></tr>
    <tr><td>GPT-5.6 Terra</td><td class="mono">67.9%</td><td class="mono">$0.0304</td><td class="mono">10.1 s</td></tr>
    <tr><td>Claude Sonnet 5</td><td class="mono">67.8%</td><td class="mono">$0.117</td><td class="mono">78 s</td></tr>
    <tr><td>Claude Opus 5</td><td class="mono">73.1%</td><td class="mono">$0.1761</td><td class="mono">37.8 s</td></tr>
    <tr><td>GPT-5.6 Sol</td><td class="mono">74.1%</td><td class="mono">$0.0836</td><td class="mono">23.3 s</td></tr>
  </tbody>
</table>
</div>
<div class="callout warn"><div class="t">Read the asterisk before you trust the table</div>
<ul>
  <li><strong>*“Accuracy” is agreement, not truth.</strong> Consensus labels were generated by GPT-6 Astra and Claude Fable 5.1 — so the benchmark measures agreement with two frontier models, and TypeSafe admits this biases toward OpenAI and Anthropic.</li>
  <li><strong>It's vendor-run.</strong> TypeSafe designed the workflows, built the harness, and ran the evaluation. No independent neutral-harness reproduction has surfaced yet.</li>
  <li><strong>The 0% error claim is structural.</strong> “Zero hallucinations” and “0% type errors” follow from the schema guarantee, not from measurement. A valid answer can still be the wrong answer with high confidence attached — this distinction was the most-argued point in the Hacker News thread after launch.</li>
  <li><strong>The community verdict:</strong> evaluate Jev on your own traffic before relying on the numbers.</li>
</ul>
</div>

<h2 id="pricing">Pricing in one table</h2>
<div class="table-wrap">
<table>
  <thead><tr><th></th><th>Jev</th><th>GPT-5.6 Terra</th><th>Claude Sonnet 5</th></tr></thead>
  <tbody>
    <tr><td>Input / 1M tokens</td><td class="mono good">$0.042</td><td class="mono">$2.00</td><td class="mono">$3.00</td></tr>
    <tr><td>Output / 1M tokens</td><td class="mono good">$0</td><td class="mono">$12.00</td><td class="mono">$15.00</td></tr>
    <tr><td>Cost per decision case</td><td class="mono good">~$0.0004</td><td class="mono">$0.0304</td><td class="mono">$0.117</td></tr>
  </tbody>
</table>
</div>
<p>Full provider-by-provider rates and an interactive cost calculator live on the <a href="/pricing/">pricing page</a>.</p>

<h2 id="limits">Limitations</h2>
<ul>
  <li><strong>No text generation.</strong> Jev cannot write an essay, an email, or a chatbot reply. Any human-facing prose still needs an LLM.</li>
  <li><strong>Text only.</strong> No image or audio input yet.</li>
  <li><strong>64K context</strong> (32K on Cloudflare). Long documents need chunking or summarizing first.</li>
  <li><strong>No arithmetic, no dates.</strong> Don't ask it to count, sum, or compute date differences — do that in code.</li>
  <li><strong>Context-sensitive.</strong> Strip tracking headers, HTML boilerplate, and unrelated metadata from the state before sending.</li>
  <li><strong>Confidently wrong is possible.</strong> Calibration helps, but a wrong answer can carry high confidence. Regression-test probabilities against historical data before automating decisions.</li>
  <li><strong>Early-access economics.</strong> Pricing and rate limits may change; TypeSafe says it can't prove the price isn't subsidized.</li>
</ul>

<h2 id="mental">The right mental model</h2>
<p>Jev isn't a cheaper LLM. It's <strong>a typed function call that happens to be intelligent</strong>: it returns a value your code can use directly, with a confidence number attached. Once you have that, a lot of code that exists only to survive and validate string output stops needing to exist at all. Within days of launch, the open-source <a href="/ecosystem/">openjev project</a> reproduced the interface pattern on a small open model — a sign the primitive may outlive any single vendor.</p>

<h2 id="access">How to try it</h2>
<p>Three routes, from zero-code to full API access, are covered step by step in our <a href="/get-access/">Get Access guide</a> — including the free-credit console path and the Vercel / Cloudflare gateways. For when to use Jev versus a frontier model, see <a href="/vs-llm/">Jev vs LLMs</a>; for concrete workflows, see <a href="/use-cases/">use cases</a>.</p>
""",
}

# ---- pricing ----
PAGES["pricing"] = {
    "title": "Jev AI Pricing 2026: Cost per Token, per Decision & vs LLMs",
    "desc": "Jev AI costs $0.042 per 1M input tokens with free output. Compare every provider (Vercel, Cloudflare, Vivgrid), see real per-decision costs, and run the calculator.",
    "crumb": CRUMB_HOME + [("Pricing", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-20 · Rates verified against provider listings on this date</p>
<h1>Jev AI Pricing: What It Actually Costs (2026)</h1>
<p class="lede">Jev's reference price is <strong>$0.042 per 1 million input tokens — about $42 per billion</strong> — and <strong>output is free</strong> on every provider, because the model returns compact typed decisions instead of generated text. This page tracks every provider's rate, translates them into real per-decision costs, and lets you compute your own bill.</p>

<h2>Official pricing</h2>
<div class="table-wrap">
<table>
  <thead><tr><th>Item</th><th>Rate</th><th>Notes</th></tr></thead>
  <tbody>
    <tr><td>Input tokens</td><td class="mono good">$0.042 / 1M</td><td>The only thing that is billed</td></tr>
    <tr><td>Output tokens</td><td class="mono good">$0</td><td>“Too cheap to meter” — answers are typed decisions, not text</td></tr>
    <tr><td>Context window</td><td class="mono">64,000</td><td>32,000 on Cloudflare; state must fit</td></tr>
    <tr><td>Typical decision</td><td class="mono">~$0.0001</td><td>Official benchmark case: $0.000081; vendor eval: $0.0004/case</td></tr>
  </tbody>
</table>
</div>
<div class="callout"><div class="t">Scale reference</div>
<p>TypeSafe's $0.042/1M input rate is roughly <strong>238x lower than “Claude Fable 5.1”</strong> and about <strong>1/48th of GPT-5.6 Terra's $2.00/1M</strong> — and those models also bill $2–$12 per 1M output tokens, which Jev never charges.</p></div>

<h2>Provider comparison</h2>
<p>Jev is served by four public providers plus TypeSafe's own console. Same model, different context limits:</p>
<div class="table-wrap">
<table>
  <thead><tr><th>Provider</th><th>Model ID</th><th>Input / 1M</th><th>Output / 1M</th><th>Context</th><th>Waitlist?</th></tr></thead>
  <tbody>
    <tr><td>TypeSafe console</td><td class="mono">jev-latest</td><td class="mono">$0.042</td><td class="mono">$0</td><td class="mono">64K</td><td>Yes (early access)</td></tr>
    <tr><td>Vercel AI Gateway</td><td class="mono">typesafe-ai/jev</td><td class="mono">$0.042</td><td class="mono">$0</td><td class="mono">64K</td><td class="good">No</td></tr>
    <tr><td>Cloudflare Workers AI</td><td class="mono">typesafe/jev</td><td class="mono">$0.042</td><td class="mono">$0</td><td class="mono">32K</td><td class="good">No</td></tr>
    <tr><td>Vivgrid</td><td class="mono">jev</td><td class="mono">$0.042</td><td class="mono">$0</td><td class="mono">64K</td><td class="good">No</td></tr>
  </tbody>
</table>
<p class="updated">Note: launch-week posts placed Jev on OpenRouter, but it is not currently listed there — verify on a provider&#8217;s own model list before building.</p>
</div>

<h2>Cost calculator</h2>
<p>Estimate your monthly bill. Jev charges input only; chat models bill both sides (assumes ~60 output tokens per decision for LLMs):</p>
<div class="calc">
  <label for="calc-decisions">Decisions per month</label>
  <input type="number" id="calc-decisions" value="100000" min="1"/>
  <label for="calc-tokens">Input tokens per decision (state + questions)</label>
  <input type="number" id="calc-tokens" value="800" min="10"/>
  <div class="calc-results">
    <div class="calc-row best"><span class="name">Jev ($0.042/1M in, out free)</span><span class="val" id="r-jev">—</span></div>
    <div class="calc-row"><span class="name">GPT-5 mini ($0.25 in / $2.00 out)</span><span class="val" id="r-mini">—</span></div>
    <div class="calc-row"><span class="name">Claude Sonnet 5 ($3.00 in / $15.00 out)</span><span class="val" id="r-sonnet">—</span></div>
    <div class="calc-row"><span class="name">Savings vs GPT-5 mini</span><span class="val" id="r-save">—</span></div>
  </div>
  <p class="calc-note">Rates from provider listings, Sep 2026. Real per-decision cost depends on your state length — keep states lean.</p>
</div>

<h2>Real-world cost reports</h2>
<ul>
  <li><strong>1,018 research papers classified</strong> for $0.08 total, 256ms median latency per paper (community report, Sep 2026).</li>
  <li><strong>Production dispatch workflow:</strong> −71% cost and −90% wall time after switching the decision step to Jev.</li>
  <li><strong>Order-flow benchmark:</strong> $0.039 per 1,000 decisions, 0.49s median on live data (independent test).</li>
  <li><strong>Video debate scoring (jevmeter):</strong> every sentence scored for about $0.05 total.</li>
</ul>

<h2>Is the price sustainable?</h2>
<p>TypeSafe is unusually candid here: it <strong>cannot prove the pricing isn't subsidized</strong> and says the long term will have to demonstrate sustainability — though it expects prices to fall rather than rise. Treat the current rate as a launch figure. Our <a href="/news/">news tracker</a> watches provider listings and will flag any change automatically.</p>

<h2>What drives your real cost</h2>
<ul>
  <li><strong>State length dominates.</strong> Cost scales with input tokens, so a 300-token lean state costs ~2.7x less than an 800-token padded one.</li>
  <li><strong>Adding questions is nearly free.</strong> Questions ride along in the same request; speculative fan-out barely moves the bill.</li>
  <li><strong>Clean states beat cheap models.</strong> Stripping HTML boilerplate and metadata reduces tokens <em>and</em> improves accuracy — the double win TypeSafe recommends in its query-design guidance.</li>
</ul>
""",
}

# ---- use-cases ----
PAGES["use-cases"] = {
    "title": "10 Jev AI Use Cases With Real Numbers (2026)",
    "desc": "Practical Jev workflows with community-reported results: agent guardrails, model routing, RAG filtering, ticket triage, moderation, LLM-as-judge, lead scoring and more.",
    "crumb": CRUMB_HOME + [("Use Cases", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-21 · Community figures are self-reported by project authors</p>
<h1>10 Jev Use Cases That Actually Work</h1>
<p class="lede">Every use case below leans on the same three things: a <strong>typed answer</strong>, a <strong>confidence number</strong>, and a price low enough to run on everything instead of a sample. If the answer already exists in the state you send, Jev is the cheapest way to extract it.</p>
<div class="callout warn"><div class="t">The one rule</div>
<p>Jev makes money on <strong>classification, not prediction</strong>. “Is this lead in our target industry?” is a Jev question. “Will this lead close?” is not — on short-horizon prediction tests, Jev did no better than a coin flip (neither did the LLMs).</p></div>

<h2>1. Agent guardrails</h2>
<p>Before an AI agent deletes a file, sends a message, or runs a command, a Jev check rates the action <em>deny / ask / allow</em> against your rules. The check costs so little that you can run it before <strong>every</strong> action instead of skipping it to save money. Community project <a href="/ecosystem/">jev-guard</a> demonstrates the pattern.</p>

<h2>2. Model routing</h2>
<p>Before a request reaches an expensive model, Jev asks one question: simple or hard. Simple requests go to a cheap model; hard ones to the expensive one. Vercel reported up to <strong>18x faster p95</strong> responses using Jev as the router — it is likely to become the default first hop in agent stacks.</p>

<h2>3. RAG filtering</h2>
<p>Retrieval pipelines pull back documents that don't help. Score each retrieved document against the real question with one Jev call, and drop weak results before they reach the model that writes the answer — better answers, fewer wasted tokens.</p>

<h2>4. Support ticket triage</h2>
<p>Tickets, emails, alerts and logs arrive in one place and need sorting before anyone acts. One Jev request picks the category, scores severity, and flags urgency together. A queue that needed a human first pass sorts itself.</p>

<h2>5. Content moderation at scale</h2>
<p>Classify comments, reviews, and messages into business-specific categories with confidence thresholds — auto-handle the confident majority, escalate the uncertain few to humans.</p>

<h2>6. LLM-as-judge, without the LLM bill</h2>
<p>When AI-written text pairs a claim with a source, Jev checks whether the source actually supports the claim. A second full model asked to “review” the first can double the cost and still invent its own mistake; one typed question checks the narrow fact instead.</p>

<h2>7. Lead scoring</h2>
<p>Score inbound leads on target-industry fit, intent strength, and spam probability in one call — then feed the verdicts into your ad platform feedback loop. Structured-decision costs make per-lead scoring viable at any volume.</p>

<h2>8. Search-term mining</h2>
<p>Classify thousands of search query reports into brand / competitor / generic / irrelevant, and auto-mine negative keywords. A decision that used to be sampled can now be exhaustive.</p>

<h2>9. Live interfaces</h2>
<p>Steve Krouse's <a href="/ecosystem/">Typewriter</a> updates 16 Jev judgments in real time as you type. When a decision is 200ms and ~$0.0001, UIs can be <em>made of</em> judgments instead of merely displaying them.</p>

<h2>10. Semantic search &amp; corpus map-reduce</h2>
<p>Filter, score and map documents across an entire corpus at a cost that permits full coverage — the community demo classified 1,018 research papers for <strong>$0.08 total</strong> at 256ms median latency.</p>

<h2>Built with Jev: the most-starred community projects</h2>
<p>Real repositories, ranked by GitHub stars (as of Sep 21, 2026). The full directory lives on the <a href="/ecosystem/">ecosystem page</a>.</p>
<div class="card-grid">
  <a class="card gh-card" href="https://github.com/OpenByteInc/QuantDinger" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/OpenByteInc/QuantDinger" alt="QuantDinger on GitHub"/><span class="tag">11.8k stars</span><h3>QuantDinger</h3><p>Open-source AI trading OS with a Jev System One integration — Jev handles the high-frequency classify / route / score calls inside the agent loop.</p></a>
  <a class="card gh-card" href="https://github.com/jaredpalmer/kev" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/jaredpalmer/kev" alt="kev on GitHub"/><span class="tag">1.0k stars</span><h3>kev</h3><p>A tiny Jev-like family of decision models built on Qwen3.5 that you can train and run yourself — the open-source take on System One.</p></a>
  <a class="card gh-card" href="https://github.com/reticlehq/reticle" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/reticlehq/reticle" alt="Reticle on GitHub"/><span class="tag">776 stars</span><h3>Reticle</h3><p>AI agents generate code but struggle to understand it — Reticle brings Jev-style typed understanding to what they build.</p></a>
  <a class="card gh-card" href="https://github.com/devagrawal09/jev-review" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/devagrawal09/jev-review" alt="jev-review on GitHub"/><span class="tag">410 stars</span><h3>jev-review</h3><p>A staged code-review workflow with a local dashboard, built on Jev.</p></a>
  <a class="card gh-card" href="https://github.com/itsmostafa/typesafe-mcp" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/itsmostafa/typesafe-mcp" alt="typesafe-mcp on GitHub"/><span class="tag">136 stars</span><h3>typesafe-mcp</h3><p>MCP connector that gives any AI agent direct access to Jev.</p></a>
  <a class="card gh-card" href="https://github.com/0xNatoshi/jev-codex-router" rel="nofollow noopener" target="_blank"><img loading="lazy" src="https://opengraph.githubassets.com/1/0xNatoshi/jev-codex-router" alt="jev-codex-router on GitHub"/><span class="tag">88 stars</span><h3>jev-codex-router</h3><p>Per-turn model and reasoning routing for Codex, decided by Jev.</p></a>
</div>

<h2>Where Jev does NOT fit</h2>
<ul>
  <li><strong>Anything generative:</strong> replies, summaries, code patches — keep your LLM.</li>
  <li><strong>Prediction:</strong> prices, churn, sales outcomes — the answer isn't in the state, and no model at this price has an edge.</li>
  <li><strong>Compound reasoning:</strong> decompose into atomic gut-check questions and combine in code, rather than asking one fuzzy mega-question.</li>
</ul>
<p>More on the decision boundary in <a href="/vs-llm/">Jev vs LLMs</a>.</p>
""",
}

# ---- get-access ----
PAGES["get-access"] = {
    "title": "How to Get Access to Jev AI (2026): Open Signup, $5 Free Credit",
    "desc": "Jev is now open to everyone — no waitlist. Sign up at console.typesafe.ai with $5 in free credit, or use it via Vercel AI Gateway and Cloudflare Workers AI. 5-minute quickstart inside.",
    "crumb": CRUMB_HOME + [("Get Access", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-20</p>
<h1>How to Get Access to Jev AI</h1>
<p class="lede"><strong>Jev opened to everyone on Sep 20, 2026 — the waitlist is gone.</strong> Sign up at console.typesafe.ai and get $5 in free credit (~120M input tokens). Prefer a gateway? Vercel and Cloudflare serve the same model. Every route ends at the same Jev.</p>

<div class="pg-notice">Want to feel the model before writing code? <a href="/playground/">Open the Playground</a> — run real decisions with your key, right in the browser.</div>
<h2 id="console">Option 1: direct signup at TypeSafe (open now)</h2>
<ol>
  <li>Go to <a href="https://console.typesafe.ai" rel="nofollow noopener" target="_blank">console.typesafe.ai</a> and register — no waitlist, no invite.</li>
  <li>New accounts get <strong>$5 in free credit</strong> — about 120 million input tokens at $0.042/1M.</li>
  <li>The console includes the web playground, API key management and usage dashboards.</li>
</ol>

<h2 id="vercel">Option 2: Vercel AI Gateway (no separate signup needed)</h2>
<p>Jev is live in the Vercel AI Gateway as <span class="mono">typesafe-ai/jev</span> since launch day. If you already build on Vercel, there's no separate signup — call it through your existing account. Pricing matches TypeSafe's native $0.042/1M rate.</p>

<h2 id="cloudflare">Option 3: Cloudflare Workers AI</h2>
<p>Cloudflare lists <span class="mono">typesafe/jev</span> with per-request edge billing. Note the context window here is <strong>32K</strong> (not 64K) — chunk long states first.</p>

<h2 id="openrouter">A note on OpenRouter</h2>
<div class="callout warn"><div class="t">Currently not listed</div>
<p>Launch-week posts placed Jev on OpenRouter, but its public models API currently returns no TypeSafe entries. Verify against a provider&#8217;s own model list before building — the reliable paths today are the TypeSafe console, the Vercel AI Gateway and Cloudflare Workers AI.</p></div>

<h2>The 5-minute quickstart</h2>
<h3>1. Try the playground (zero code)</h3>
<p>Open <span class="mono">console.typesafe.ai/playground</span>: paste a text state, write a plain-language question, pick the answer type (Choice / Score / Noul), and run. Results come back sub-second with confidence scores. The official starter: paste “I've been trying to connect my Stripe account for 3 days and it keeps failing. I'm losing sales.” and ask “Does this message express urgency?”</p>
<h3>2. Call the API</h3>
<pre><code>curl https://api.typesafe.ai/v1/systemone \\
  -H <span class="c-str">"Authorization: Bearer $JEV_API_KEY"</span> \\
  -d '{
    <span class="c-key">"model"</span>: <span class="c-str">"jev-latest"</span>,
    <span class="c-key">"state"</span>: <span class="c-str">"The checkout page throws a 500 on Safari only."</span>,
    <span class="c-key">"questions"</span>: {
      <span class="c-key">"category"</span>: { <span class="c-key">"type"</span>: <span class="c-str">"choice"</span>,
                    <span class="c-key">"options"</span>: [<span class="c-str">"billing"</span>, <span class="c-str">"technical"</span>, <span class="c-str">"sales"</span>] }
    }
  }'</code></pre>
<h3>3. Use an SDK</h3>
<p>Official Python and JavaScript/TypeScript SDKs are available, plus the <span class="mono">langchain-typesafe</span> package and the Vercel AI SDK integration (<span class="mono">@ai-sdk/typesafe</span>). The TypeScript evaluate pattern:</p>
<pre><code><span class="c-key">import</span> { evaluate } <span class="c-key">from</span> <span class="c-str">'@typesafe-ai/sdk'</span>;

<span class="c-key">const</span> verdict = <span class="c-key">await</span> <span class="c-fn">evaluate</span>({
  model: <span class="c-str">'typesafe-ai/jev'</span>,
  state: ticketText,
  questions: {
    category: { type: <span class="c-str">'choice'</span>, options: [<span class="c-str">'billing'</span>,<span class="c-str">'technical'</span>,<span class="c-str">'sales'</span>,<span class="c-str">'spam'</span>] },
  },
});

<span class="c-com">// Your code owns the policy:</span>
<span class="c-key">if</span> (verdict.category.value === <span class="c-str">'spam'</span> &amp;&amp; verdict.confidence &gt; 0.90) archive(ticketText);</code></pre>

<h2>Rate limits &amp; production notes</h2>
<ul>
  <li>Early-access defaults: ~<strong>250,000 tokens/sec</strong> and ~<strong>1,200 requests/min</strong>; enterprise tiers available.</li>
  <li>Keep states lean — strip HTML and metadata. Fewer tokens, better accuracy.</li>
  <li>Ask atomic questions; combine probabilities in code.</li>
  <li>Regression-test calibration on 100–500 historical cases before automating.</li>
</ul>
<p>Not sure what to build first? Start with <a href="/use-cases/">ticket triage or email routing</a> — low risk, immediate payoff. And check <a href="/vs-llm/">when Jev shouldn't be used</a> at all.</p>

<h2>Jev AI access FAQ</h2>
{FAQ_TEASER_ACCESS}
<p><a href="/faq/">Read the full Jev AI FAQ →</a></p>
""",
}

# ---- vs-llm ----
PAGES["vs-llm"] = {
    "title": "Jev AI vs LLMs: When to Use Each (Honest 2026 Guide)",
    "desc": "Jev or a chat LLM? A decision table for routing, classification and generation workloads, a hybrid architecture pattern, and the honest limits of each side.",
    "crumb": CRUMB_HOME + [("Jev vs LLMs", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-20</p>
<h1>Jev AI vs LLMs: When to Use Each</h1>
<p class="lede"><strong>The one-line answer:</strong> if the answer already exists in the input and one of a known set of options is correct, use Jev. If the answer has to be written — prose, code, a summary, a plan — use an LLM. Most real systems want both.</p>

<h2>Side-by-side</h2>
<div class="table-wrap">
<table>
  <thead><tr><th></th><th>Jev (System One)</th><th>Chat LLM (GPT / Claude / Gemini)</th></tr></thead>
  <tbody>
    <tr><td>Returns</td><td>Typed decision + confidence</td><td>Free-form text</td></tr>
    <tr><td>Input price / 1M</td><td class="mono good">$0.042</td><td class="mono">$0.25 – $3.00+</td></tr>
    <tr><td>Output price / 1M</td><td class="mono good">$0</td><td class="mono">$2 – $15+</td></tr>
    <tr><td>Latency</td><td class="mono good">70–500 ms</td><td class="mono">2 – 80 s</td></tr>
    <tr><td>Hallucinated text</td><td class="good">Impossible by construction</td><td class="bad">An inherent risk</td></tr>
    <tr><td>Invalid answer format</td><td class="good">0% (schema-guaranteed)</td><td class="bad">0.58% – 45.5% observed</td></tr>
    <tr><td>Can write text</td><td class="bad">Never</td><td class="good">That's the point</td></tr>
    <tr><td>Open-ended reasoning</td><td class="bad">No</td><td class="good">Yes</td></tr>
    <tr><td>Images / audio input</td><td class="bad">No (text only)</td><td class="good">Usually</td></tr>
    <tr><td>Context window</td><td class="mono">64K (32K on Cloudflare)</td><td class="mono">128K – 1M+</td></tr>
  </tbody>
</table>
</div>

<h2>The decision table</h2>
<div class="table-wrap">
<table>
  <thead><tr><th>Workload</th><th>Winner</th><th>Why</th></tr></thead>
  <tbody>
    <tr><td>Ticket / email triage</td><td class="good">Jev</td><td>Bounded categories, huge volume, cost matters</td></tr>
    <tr><td>Agent tool-call approval</td><td class="good">Jev</td><td>Every call needs checking; a $0.0001 check beats a skipped one</td></tr>
    <tr><td>Simple/hard request routing</td><td class="good">Jev</td><td>Saves premium tokens for requests that need them</td></tr>
    <tr><td>RAG relevance filtering</td><td class="good">Jev</td><td>Score-then-drop before generation</td></tr>
    <tr><td>Drafting replies &amp; summaries</td><td class="good">LLM</td><td>Generation is the LLM's job</td></tr>
    <tr><td>Multi-step open reasoning</td><td class="good">LLM</td><td>Jev only does bounded judgment</td></tr>
    <tr><td>“Will price/churn/sales move?”</td><td class="warn-c">Neither</td><td>Prediction isn't in the input; tested at coin-flip level</td></tr>
    <tr><td>Arithmetic &amp; date math</td><td class="warn-c">Plain code</td><td>Don't use either model for math</td></tr>
  </tbody>
</table>
</div>

<h2>The hybrid architecture (what production looks like)</h2>
<pre><code>Incoming request (webhook / form / ticket)
        │
        ▼
  Jev decision layer        ~200ms, ~$0.0001
  (category · urgency · spam? · route?)
        │
        ├─ high confidence, standard action ──► deterministic code acts
        ├─ low confidence / complex ──────────► escalate to human
        └─ generation required ───────────────► frontier LLM
                                                  │
                                                  ▼
                                    optional Jev QA pass (verify claims)</code></pre>
<p>This pattern keeps control flow in your codebase, avoids fragile multi-turn prompt loops, eliminates schema validation errors, and reserves expensive frontier inference for requests that actually require it. LangChain's own guide frames Jev the same way: <strong>a complement to LLMs, not a replacement</strong>.</p>

<h2>What Jev cannot do (be honest with yourself)</h2>
<ul>
  <li>No text, no explanations, no empathy — any human-facing prose needs an LLM.</li>
  <li>No open-ended reasoning; it judges, it doesn't think through problems.</li>
  <li>Text-only input; 64K context; no math or dates.</li>
  <li>A valid answer can still be wrong with high confidence — calibrate on your own data.</li>
  <li>Benchmarks are vendor-run; verify on your traffic before production trust.</li>
</ul>

<h2>Bottom line</h2>
<p>The trade is <strong>cost, not accuracy</strong>: Jev lands within a point or two of mid-tier frontier models on bounded workflows while costing 1–2 orders of magnitude less. Run the cheap judge everywhere, spend the expensive thinker rarely. Check the <a href="/pricing/">cost calculator</a> with your real volumes, and pick a first workflow from the <a href="/use-cases/">use-case playbook</a>.</p>
""",
}

# ---- news ----
PAGES["news"] = {
    "title": "Jev AI News & Updates — Live Tracker (2026)",
    "desc": "Every Jev update in one timeline: launch news, access changes, provider listings, price changes, benchmark analyses and community projects — automatically tracked.",
    "crumb": CRUMB_HOME + [("News", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-20 · This page is refreshed automatically as new sources appear</p>
<h1>Jev AI News &amp; Updates</h1>
<p class="lede">A running timeline of everything that matters about Jev — official announcements, provider rollouts, independent analyses, and community milestones. Each item links to its source; vendor-reported figures are marked as such.</p>
<div class="timeline">
{NEWS_FULL}
</div>
""",
}

# ---- ecosystem ----
PAGES["ecosystem"] = {
    "title": "Jev AI Ecosystem: Open-Source Projects & Community Tools",
    "desc": "The Jev project directory: openjev, jev-ultrafast, jev-guard, pg-jev, HA-Jev, jevmeter and more — what each does, and who built it.",
    "crumb": CRUMB_HOME + [("Ecosystem", None)],
    "schema": [],
    "body": """
<p class="updated">Last updated: 2026-09-20 · Project descriptions from public demos and author posts</p>
<h1>The Jev AI Ecosystem</h1>
<p class="lede">Within days of launch, developers started building on Jev's typed-decision primitive — agents, guardrails, database filters, games, and even an open-source reproduction of the interface itself. This directory tracks the notable ones.</p>

<h2>Open-source reproduction</h2>
<div class="card-grid">
  <div class="card"><span class="tag">Reference impl.</span><h2>openjev</h2><p>Reproduces the Jev interface pattern on a small open model by reading typed option probabilities off the logits. The community's answer to “is this a durable primitive or a vendor wrapper?” — apparently durable.</p></div>
</div>

<h2>Agents</h2>
<div class="card-grid">
  <div class="card"><span class="tag">Browser</span><h2>jev-ultrafast</h2><p>Browser Use's agent with Jev as its decision layer — completed a Zürich→London Google Flights search in 7.1 seconds.</p></div>
  <div class="card"><span class="tag">Mobile</span><h2>mobile-jev</h2><p>Droidrun's phone agent drove Uber on a real Android device: 9 actions in ~21 seconds (no booking completed).</p></div>
  <div class="card"><span class="tag">Computer use</span><h2>typesafe-computer-use</h2><p>Computer-use agent with Jev as the cheap gatekeeper for every action.</p></div>
  <div class="card"><span class="tag">Games</span><h2>heist-one</h2><p>Jev runs the guard AI logic in a heist game demo — decisions, not scripts.</p></div>
</div>

<h2>Infrastructure &amp; tooling</h2>
<div class="card-grid">
  <div class="card"><span class="tag">Safety</span><h2>jev-guard</h2><p>Rates every agent tool call as deny / ask / allow against your rules before execution.</p></div>
  <div class="card"><span class="tag">Databases</span><h2>pg-jev</h2><p>Adds plain-language filtering to Postgres queries via Jev decisions.</p></div>
  <div class="card"><span class="tag">Smart home</span><h2>HA-Jev</h2><p>Turns Jev answers into Home Assistant entities for smart-home logic.</p></div>
  <div class="card"><span class="tag">Media</span><h2>jevmeter</h2><p>Scores every sentence of a video debate for about $0.05 total.</p></div>
  <div class="card"><span class="tag">Realtime UI</span><h2>Typewriter</h2><p>Steve Krouse's live typing demo — 16 Jev judgments update in real time as you type.</p></div>
  <div class="card"><span class="tag">Experiments</span><h2>jev-trader</h2><p>Market-signal experiments. Independent testing showed Jev does no better than a coin flip on short-horizon prediction — see <a href="/use-cases/">the rule</a>.</p></div>
</div>

<h2>Want to be listed?</h2>
<p>Building something with Jev? It'll likely show up on Hacker News or X — our tracker picks it up from there and adds it here automatically, or reach out with a link.</p>
""",
}

# ---- faq ----
_faq_body, _faq_schema = faq_html_and_schema()
PAGES["faq"] = {
    "title": "Jev AI FAQ: 20 Questions About TypeSafe's System One Model",
    "desc": "Straight answers about Jev: what it is, public access, pricing, rate limits, hallucination guarantees, benchmark reliability, and where the information comes from.",
    "crumb": CRUMB_HOME + [("FAQ", None)],
    "schema": [_faq_schema],
    "body": """
<p class="updated">Last updated: 2026-09-20</p>
<h1>Jev AI FAQ: 20 Questions, Straight Answers</h1>
<p class="lede">Everything people are actually asking about Jev, answered without marketing gloss. Where a claim is TypeSafe's own, we say so.</p>
""" + _faq_body,
}

# live data overrides (written by update_news.py)
import json as _json, os as _os
_news_file = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "data", "news.json")
if _os.path.exists(_news_file):
    _live = _json.load(open(_news_file, encoding="utf-8"))
    NEWS = [
        (i["date"], i["title"],
         i["summary"] + (f' <a href="{(i.get("url") or "").replace("&", "&amp;")}">Read source →</a>' if i.get("url") else ""),
         i["source"])
        for i in _live
    ]
    from datetime import date as _date
    PAGES["news"]["body"] = PAGES["news"]["body"].replace(
        "Last updated: 2026-09-20", f"Last updated: {_date.today().isoformat()}")

# news 页 ItemList schema：给 Google 富数据 + 新鲜度信号
if _os.path.exists(_news_file):
  PAGES["news"]["schema"] = [{
    "@context": "https://schema.org", "@type": "ItemList",
    "name": "Jev news timeline",
    "itemListElement": [
        {"@type": "ListItem", "position": i + 1,
         "name": i2["title"], "url": i2.get("url") or "https://jev-ai.live/news/"}
          for i, i2 in enumerate(_live[:20])
      ],
  }]

# inject news into home + news page
NEWS_PREVIEW = "".join(
    f'<div class="tl-item"><div class="date">{d}</div><h3>{t}</h3><p>{s}</p><div class="src">Source: {src}</div></div>'
    for d, t, s, src in NEWS[:3]
)
PAGES["index"]["body"] = PAGES["index"]["body"].replace("{NEWS_PREVIEW}", NEWS_PREVIEW)

# FAQ teasers (visible block + FAQPage schema) on home and get-access
_idx_teaser_html, _idx_teaser_schema = faq_teaser([0, 1, 4, 8, 12])
PAGES["index"]["body"] = PAGES["index"]["body"].replace("{FAQ_TEASER}", _idx_teaser_html)
PAGES["index"]["schema"].append(_idx_teaser_schema)

_acc_teaser_html, _acc_teaser_schema = faq_teaser([4, 5, 6, 7])
PAGES["get-access"]["body"] = PAGES["get-access"]["body"].replace("{FAQ_TEASER_ACCESS}", _acc_teaser_html)
PAGES["get-access"]["schema"].append(_acc_teaser_schema)

NEWS_FULL = "".join(
    f'<div class="tl-item"><div class="date">{d}</div><h3>{t}</h3><p>{s}</p><div class="src">Source: {src}</div></div>'
    for d, t, s, src in NEWS
)
PAGES["news"]["body"] = PAGES["news"]["body"].replace("{NEWS_FULL}", NEWS_FULL)

# ---- playground (BYOK interactive tool) ----
PAGES["playground"] = {
    "title": "Jev AI Playground — Try the Jev Model Online With Your Own Key | Jev Hub",
    "desc": "Run real Jev (TypeSafe System One) decisions in your browser: build Choice, Score and Noul questions, use your own API key (stored locally, never sent to us), and see live probabilities, confidence and per-call cost.",
    "crumb": [("Home", "/"), ("Playground", None)],
    "wide": True,
    "schema": [{
        "@context": "https://schema.org", "@type": "WebApplication",
        "name": "Jev Playground", "url": "https://jev-ai.live/playground/",
        "applicationCategory": "DeveloperApplication", "operatingSystem": "Web",
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "description": "Browser playground for the Jev model: build typed questions and run real decisions with your own TypeSafe API key.",
    }],
    "body": """<div class="hero pg-hero">
  <div class="kicker">BYOK · Your key stays in your browser</div>
  <h1>Jev AI Playground</h1>
  <p class="sub">Build typed questions — <strong>Choice</strong>, <strong>Score</strong>, <strong>Noul</strong> — and run them against the live Jev API with <strong>your own API key</strong>. See exactly what your code would receive: answers, probabilities, confidence, tokens and cost. The key is stored in this browser only and sent directly to api.typesafe.ai — never to us.</p>
</div>

<div id="pg-app">
<div class="pg-notice" id="pg-nokey"><strong>No API key? Just hit Run.</strong> The site sponsors <strong>5 free plays a day</strong>, no signup. Want your own key? TypeSafe registration is open with <a href="/get-access/">$5 in free credit</a>.</div>

<div class="pg-keybar">
  <label>TypeSafe API key
    <input type="password" id="pg-key" placeholder="jev_..." autocomplete="off" spellcheck="false"/>
  </label>
  <label>Model
    <select id="pg-model">
      <option value="jev-latest">jev-latest</option>
      <option value="jev-preview">jev-preview</option>
    </select>
  </label>
  <button class="pg-ghost" id="pg-savekey">Save key</button>
  <button class="pg-ghost" id="pg-forget">Forget key</button>
</div>

<div class="pg-cases" id="pg-cases">
  <span class="pg-caseslabel">Try a scenario</span>
  <button class="pg-case is-on" data-case="support">Support triage</button>
  <button class="pg-case" data-case="review">Review score</button>
  <button class="pg-case" data-case="moderation">Moderation</button>
  <button class="pg-case" data-case="lead">Lead routing</button>
  <button class="pg-case" data-case="hook">Title test</button>
  <button class="pg-case" data-case="ai_flavor">AI flavor</button>
  <button class="pg-case" data-case="feed_filter">Topic filter</button>
  <button class="pg-case" data-case="read_triage">Read triage</button>
  <button class="pg-case" data-case="code_review">Code review</button>
  <button class="pg-case" data-case="cmd_safety">Cmd safety</button>
  <button class="pg-case" data-case="inbox">Inbox triage</button>
  <button class="pg-case" data-case="resume">Resume screen</button>
</div>
<p class="pg-hint">12 scenarios covering all three question types (choice / score / noul) — load one, run it, then tweak it into your own.</p>

<div class="pg-layout">
  <div class="pg-col">
  <section class="pg-card">
    <h2>1 · State</h2>
    <textarea id="pg-state" class="pg-textarea" rows="7" placeholder="Paste the ticket, review, passage or JSON object that Jev should judge."></textarea>
    <div class="pg-countrow" id="pg-countrow"><span id="pg-chars">0 characters</span><span class="pg-sep">·</span><span id="pg-toks">≈ 0 tokens</span><span class="pg-sep">·</span><span class="pg-countnote">64K token limit per request</span></div>
    <p class="pg-hint">Plain text or JSON — all questions share this state and are answered independently in a single call.</p>
  </section>
  <section class="pg-card">
    <h2>2 · Questions <span class="pg-p" id="pg-count"></span></h2>
    <div id="pg-questions"></div>
    <div class="pg-empty" id="pg-empty">No questions yet — click <strong>Load example</strong> above, or add your own below.</div>
    <button class="pg-ghost" id="pg-addq">+ Add question (max 8)</button>
  </section>
  </div>
  <div class="pg-col">
    <div class="pg-runrow">
      <button class="pg-run" id="pg-run">Run decision</button>
      <span class="pg-status" id="pg-status"></span>
    </div>

    <section class="pg-card pg-results" id="pg-results" hidden>
      <h2>3 · Results</h2>
      <div id="pg-answers"></div>
      <div class="pg-meta" id="pg-meta"></div>
      <div id="pg-errbox"></div>
    </section>
  </div>
</div>

<section class="pg-card pg-curl" id="pg-curlbox" hidden>
  <h2>Or run it from your terminal</h2>
  <p class="pg-hint" style="margin-bottom:10px">The exact same request as a shell command — useful if the browser blocks the direct call (CORS) or you prefer the terminal:</p>
  <pre id="pg-curl"></pre>
  <button class="pg-ghost pg-copy" id="pg-copy">Copy curl command</button>
</section>
</div>

<section>
  <div class="kicker">How it works</div>
  <h2>What just happened here</h2>
  <p>This page is a thin client for the official <code>POST /v1/systemone</code> endpoint. You supply the key; the request goes from your browser straight to api.typesafe.ai. We never see your key, your state, or the answers. Everything you type is autosaved in your browser's localStorage so a refresh does not lose your work.</p>
  <p>One call carries <strong>one state and all of its questions</strong> — the same pattern you would use in production. The response mirrors it: one typed answer per question, each with probabilities and a confidence value your code can gate on.</p>
</section>

<section>
  <div class="kicker">Primitives</div>
  <h2>The three question types</h2>
  <h3>Choice — pick one of N options</h3>
  <p>2–255 named options, optionally with a description each. Best for routing and classification: "which team handles this?", "is this passage relevant or not?". The answer is the winning option plus a probability for every option.</p>
  <h3>Score — grade on an ordered scale</h3>
  <p>2–10 levels ordered low to high, starting at 0. Best for graded judgments: frustration, urgency, quality. Write the boundary of each level into its description — that is what makes scores comparable across inputs.</p>
  <h3>Noul — yes/no with a probability</h3>
  <p>The cheapest primitive: a single binary judgment, returned as the probability of yes. Optionally describe what yes and no mean. Use it for guardrails: "does this need a human?", "is this request sensitive?".</p>
</section>

<section>
  <div class="kicker">Good to know</div>
  <h2>Limits, cost and honesty</h2>
  <ul>
    <li><strong>Billing is input-only</strong> at $0.042 per 1M tokens; output is free. This page shows the per-call token count and cost after every run.</li>
    <li><strong>Limits</strong>: up to 64K tokens per request, 32K combined for state plus the longest question, ~1,200 requests/minute on direct access (subject to TypeSafe's current docs).</li>
    <li><strong>A valid answer can still be wrong</strong> — Jev guarantees schema validity, not correctness. Gate actions on confidence bands: act automatically when high, review in the middle, escalate when low.</li>
    <li><strong>Write atomic questions.</strong> One question = one judgment. "Score this startup" mixes market, tech and team — split it into several Score questions and combine in your code.</li>
    <li><strong>No key yet?</strong> Registration is open with $5 in free credit — see <a href="/get-access/">Get access</a>.</li>
  </ul>
</section>

<script>
(function(){
  var API = "https://api.typesafe.ai/v1/systemone";
  var PRICE = 0.042;
  var $ = function(s){ return document.querySelector(s); };
  var esc = function(s){ return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); };
  var NL = String.fromCharCode(10), BS = String.fromCharCode(92);
  var keyEl = $("#pg-key"), modelEl = $("#pg-model"), stateEl = $("#pg-state");
  var listEl = $("#pg-questions"), countEl = $("#pg-count"), statusEl = $("#pg-status");
  var resultsEl = $("#pg-results"), answersEl = $("#pg-answers"), metaEl = $("#pg-meta"), errEl = $("#pg-errbox");
  var curlBox = $("#pg-curlbox"), curlEl = $("#pg-curl");
  var countRow = $("#pg-countrow"), charsEl = $("#pg-chars"), toksEl = $("#pg-toks");
  var lastQs = null, isFreeRun = false;

  function updateCount(){
    var n = stateEl.value.length;
    var tok = Math.ceil(n / 4);
    charsEl.textContent = n + (n === 1 ? " character" : " characters");
    toksEl.textContent = "≈ " + tok.toLocaleString() + " tokens";
    countRow.className = "pg-countrow" + (tok > 60000 ? " warn" : "");
  }

  function setStatus(msg, isErr){ statusEl.textContent = msg; statusEl.className = isErr ? "pg-status err" : "pg-status"; }

  function optRow(kind, name, desc){
    var d = document.createElement("div"); d.className = "pg-optrow";
    if(kind === "choice"){
      d.innerHTML = '<input class="pg-input pg-optname" placeholder="option_key" value="' + esc(name || "") + '"/><input class="pg-input pg-optdesc" placeholder="description (optional)" value="' + esc(desc || "") + '"/><button class="pg-optdel" title="remove">✕</button>';
    } else if(kind === "score"){
      d.innerHTML = '<span class="pg-lvlno"></span><input class="pg-input pg-optdesc" placeholder="level description (low to high)" value="' + esc(desc || "") + '"/><button class="pg-optdel" title="remove">✕</button>';
    } else {
      d.innerHTML = '<span class="pg-lvlno">' + (name === "true" ? "YES" : "NO") + '</span><input class="pg-input pg-optdesc" placeholder="' + (name === "true" ? "yes means..." : "no means...") + '" value="' + esc(desc || "") + '"/><span style="min-width:21px"></span>';
    }
    var b = d.querySelector(".pg-optdel");
    if(b) b.addEventListener("click", function(){ d.remove(); renumber(); persist(); });
    return d;
  }

  function qCard(q){
    q = q || {};
    var card = document.createElement("div"); card.className = "pg-qcard";
    card.innerHTML = '<div class="pg-qhead"><input class="pg-input pg-qid" placeholder="question_id" value="' + esc(q.id || "") + '"/><select class="pg-select pg-qtype"><option value="choice">Choice</option><option value="score">Score</option><option value="noul">Noul (yes/no)</option></select><button class="pg-qdel" title="remove question">✕</button></div>'
      + '<textarea class="pg-textarea pg-qinstr" rows="2" placeholder="Instructions: what exactly should Jev decide? Be specific.">' + esc(q.instructions || "") + '</textarea>'
      + '<div class="pg-qopts"></div><button class="pg-ghost pg-addopt">+ Add option</button>';
    var typeSel = card.querySelector(".pg-qtype"); typeSel.value = q.type || "choice";
    var opts = card.querySelector(".pg-qopts"), addBtn = card.querySelector(".pg-addopt");
    function rebuild(){
      opts.innerHTML = "";
      var t = typeSel.value;
      if(t === "choice"){
        var crit = (q && q.criteria && !Array.isArray(q.criteria)) ? q.criteria : null;
        var keys = crit ? Object.keys(crit) : ["", ""];
        if(!keys.length) keys = ["", ""];
        keys.forEach(function(k){ opts.appendChild(optRow("choice", k, crit ? crit[k] : "")); });
        addBtn.style.display = "";
      } else if(t === "score"){
        var lv = (q && Array.isArray(q.criteria) && q.criteria.length) ? q.criteria : ["", ""];
        lv.forEach(function(v){ opts.appendChild(optRow("score", null, v)); });
        addBtn.style.display = "";
      } else {
        var c = (q && q.criteria && !Array.isArray(q.criteria)) ? q.criteria : {};
        opts.appendChild(optRow("noul", "true", c["true"] || ""));
        opts.appendChild(optRow("noul", "false", c["false"] || ""));
        addBtn.style.display = "none";
      }
      renumber();
    }
    typeSel.addEventListener("change", function(){ q = null; rebuild(); persist(); });
    addBtn.addEventListener("click", function(){
      opts.appendChild(optRow(typeSel.value === "score" ? "score" : "choice", "", ""));
      renumber(); persist();
    });
    card.querySelector(".pg-qdel").addEventListener("click", function(){ card.remove(); renumber(); persist(); });
    card.addEventListener("input", persist);
    card._rebuild = rebuild;
    rebuild();
    return card;
  }

  function renumber(){
    var cards = listEl.querySelectorAll(".pg-qcard");
    countEl.textContent = cards.length + " / 8";
    var em = document.getElementById("pg-empty"); if(em) em.style.display = cards.length ? "none" : "";
    cards.forEach(function(card){
      if(card.querySelector(".pg-qtype").value !== "score") return;
      card.querySelectorAll(".pg-optrow").forEach(function(r, i){ r.querySelector(".pg-lvlno").textContent = i; });
    });
  }

  function collect(){
    var qs = {};
    listEl.querySelectorAll(".pg-qcard").forEach(function(card, i){
      var id = card.querySelector(".pg-qid").value.trim().replace(/[^a-zA-Z0-9_]/g, "_") || ("q" + (i + 1));
      while(qs[id]) id = id + "_x";
      var type = card.querySelector(".pg-qtype").value;
      var q = { type: type, instructions: card.querySelector(".pg-qinstr").value.trim() };
      var rows = card.querySelectorAll(".pg-optrow");
      if(type === "choice"){
        var c = {};
        rows.forEach(function(r){
          var n = r.querySelector(".pg-optname").value.trim();
          if(n) c[n] = r.querySelector(".pg-optdesc").value.trim();
        });
        if(Object.keys(c).length) q.criteria = c;
      } else if(type === "score"){
        var lv = [];
        rows.forEach(function(r){ lv.push(r.querySelector(".pg-optdesc").value.trim()); });
        if(lv.length >= 2) q.criteria = lv;
      } else {
        var y = rows[0].querySelector(".pg-optdesc").value.trim();
        var n = rows[1].querySelector(".pg-optdesc").value.trim();
        if(y || n){ q.criteria = {}; if(y) q.criteria["true"] = y; if(n) q.criteria["false"] = n; }
      }
      qs[id] = q;
    });
    return qs;
  }

  function snapshot(){
    var qs = [];
    listEl.querySelectorAll(".pg-qcard").forEach(function(card){
      var item = { id: card.querySelector(".pg-qid").value, type: card.querySelector(".pg-qtype").value, instructions: card.querySelector(".pg-qinstr").value, opts: [] };
      card.querySelectorAll(".pg-optrow").forEach(function(r){
        var n = r.querySelector(".pg-optname"), d = r.querySelector(".pg-optdesc");
        item.opts.push({ name: n ? n.value : null, desc: d ? d.value : null });
      });
      qs.push(item);
    });
    return { state: stateEl.value, model: modelEl.value, questions: qs };
  }
  function persist(){ try{ localStorage.setItem("jev_pg_draft", JSON.stringify(snapshot())); }catch(e){} }

  function restoreDraft(){
    try{
      var d = JSON.parse(localStorage.getItem("jev_pg_draft") || "null");
      if(!d || !d.questions || !d.questions.length) return false;
      if(d.model) modelEl.value = d.model;
      if(d.state) stateEl.value = d.state;
      listEl.innerHTML = "";
      d.questions.forEach(function(qi){
        var q = { id: qi.id || "", type: qi.type || "choice", instructions: qi.instructions || "" };
        if(qi.type === "choice" && qi.opts){ q.criteria = {}; qi.opts.forEach(function(o){ if(o.name) q.criteria[o.name] = o.desc || ""; }); }
        if(qi.type === "score" && qi.opts){ q.criteria = qi.opts.map(function(o){ return o.desc || ""; }); }
        if(qi.type === "noul" && qi.opts){ q.criteria = { "true": (qi.opts[0] || {}).desc || "", "false": (qi.opts[1] || {}).desc || "" }; }
        listEl.appendChild(qCard(q));
      });
      return true;
    }catch(e){ return false; }
  }

  function restoreKey(){
    try{
      var k = localStorage.getItem("jev_pg_key");
      if(k){ keyEl.value = k; $("#pg-nokey").style.display = "none"; }
    }catch(e){}
  }

  var CASES = {
    hook: {
      state: "Three candidate titles — A: I automated 200 support tickets a week with Jev. B: Judgment models are the most underrated AI trend. C: Stop making LLMs do judgment, it is slow and expensive.",
      questions: [
        { id: "best_hook", type: "choice", instructions: "Which title has the strongest hook?", criteria: { a: "A — number plus result, concrete", b: "B — hype framing, emotion-driven", c: "C — contrarian, hits a pain point" } },
        { id: "specificity", type: "score", instructions: "How concrete and credible is the title?", criteria: ["Vague slogan, no information", "Some concrete detail", "Number plus result, very specific"] },
        { id: "clickbait_risk", type: "noul", instructions: "Does this title carry clickbait risk?" }
      ]
    },
    ai_flavor: {
      state: "In today's fast-paced digital era, productivity gains come not from working longer hours but from the deep adoption of tools. It is not merely a tool — it is an entirely new paradigm. In short, mastering tools is the key to staying competitive.",
      questions: [
        { id: "ai_flavor", type: "score", instructions: "How strong is the AI flavor in this paragraph?", criteria: ["Reads human", "Some template tone but acceptable", "Obviously AI-generated"] },
        { id: "main_issue", type: "choice", instructions: "What is the most prominent problem?", criteria: { repetition: "Repeated conclusions / filler", vague: "Vague, no concrete specifics", template: "Not-X-but-Y template phrasing" } },
        { id: "needs_rewrite", type: "noul", instructions: "Does this paragraph need a rewrite?" }
      ]
    },
    feed_filter: {
      state: "HN post: Show HN — I built a 2000-line Go proxy that turns any web page into RSS, supports paywalled sites, ships with a browser extension and a deploy guide.",
      questions: [
        { id: "audience_fit", type: "choice", instructions: "Who is this content most worth surfacing to?", criteria: { builders: "Developers shipping products", general: "General AI enthusiasts", skip: "Not a fit for our readers" } },
        { id: "tech_depth", type: "score", instructions: "How deep is it technically?", criteria: ["Overview level", "Implementation details", "Source-level, reproducible"] },
        { id: "worth_writing", type: "noul", instructions: "Is it worth writing an article about today?" }
      ]
    },
    read_triage: {
      state: "Long read: RLCD training for System One models, explained. 4000 words, 3 architecture diagrams, one reproducible experimental setup.",
      questions: [
        { id: "action", type: "choice", instructions: "What should the reader do with this item?", criteria: { save: "Save and read carefully", skim: "Skim the takeaway only", hide: "Hide it" } },
        { id: "relevance", type: "score", instructions: "How relevant to AI engineering practice?", criteria: ["Tangential", "Relevant", "Core"] },
        { id: "evergreen", type: "noul", instructions: "Is it evergreen (still valuable in a year)?" }
      ]
    },
    code_review: {
      state: "diff: timeout changed from 30 to a configurable env var; a new SQL query interpolates user input directly — SELECT * FROM users WHERE name = user_input.",
      questions: [
        { id: "category", type: "choice", instructions: "What is the main risk category of this change?", criteria: { security: "Security (injection / authz)", correctness: "Correctness or logic", style: "Style / maintainability" } },
        { id: "severity", type: "score", instructions: "How severe is it?", criteria: ["Negligible", "Should fix", "Must block the merge"] },
        { id: "needs_human", type: "noul", instructions: "Does this need further human review?" }
      ]
    },
    cmd_safety: {
      state: "rm -rf ./node_modules && rm -rf ~/Library/Caches/* && git push --force origin main",
      questions: [
        { id: "verdict", type: "choice", instructions: "What should happen with this command?", criteria: { allow: "Run it", confirm: "Confirm with the user first", block: "Refuse to run" } },
        { id: "blast_radius", type: "score", instructions: "How large is the blast radius?", criteria: ["Current directory only", "User home or global scope", "Irreversible damage"] },
        { id: "reversible", type: "noul", instructions: "Is the operation reversible?" }
      ]
    },
    inbox: {
      state: "Message from the boss: send me the API evaluation conclusion before tomorrow's standup — the CTO wants to see it too.",
      questions: [
        { id: "priority", type: "choice", instructions: "Which handling priority does this message belong to?", criteria: { now: "Handle immediately", today: "Handle today", later: "Defer or ignore" } },
        { id: "effort", type: "score", instructions: "How much effort to handle?", criteria: ["Under a minute", "About 10 minutes", "Needs dedicated time"] },
        { id: "needs_reply", type: "noul", instructions: "Does it require a reply?" }
      ]
    },
    resume: {
      state: "Candidate: 5 years of backend experience, 3 of them Python/FastAPI, led a gateway rebuild handling tens of millions of requests a day, no LLM experience, salary expectation 20% above budget.",
      questions: [
        { id: "fit", type: "choice", instructions: "How good is the fit for the Senior Backend Engineer (AI preferred) role?", criteria: { strong: "Strong fit, schedule interview", partial: "Partial fit, keep as backup", weak: "Not a fit" } },
        { id: "salary_risk", type: "score", instructions: "How risky is the salary expectation?", criteria: ["Within budget", "Slightly over, negotiable", "Clearly over"] },
        { id: "interview", type: "noul", instructions: "Worth a first-round interview?" }
      ]
    },
    support: {
      state: "Hi, I have been trying to connect my Stripe account for 3 days and it keeps failing. I am losing sales. Please help ASAP.",
      questions: [
        { id: "department", type: "choice", instructions: "Which team should handle this ticket?", criteria: { billing: "Payments, invoicing, refunds", technical: "Bugs, outages, integrations", sales: "Pricing, upgrades, new accounts" } },
        { id: "frustration", type: "score", instructions: "How frustrated is the customer?", criteria: ["Calm, just stating facts", "Frustrated but civil", "Very angry, strong language"] },
        { id: "is_urgent", type: "noul", instructions: "Does this message express urgency or time-sensitivity?" }
      ]
    },
    review: {
      state: "The headphones arrived fast and the sound is great, but the right earcup creaks whenever I turn my head. For this price I expected better build quality. Battery easily lasts a full week though. I probably would not buy them again at full price.",
      questions: [
        { id: "sentiment", type: "choice", instructions: "What is the overall sentiment of this review?", criteria: { positive: "Praise dominates", neutral: "Mixed or purely factual", negative: "Complaints dominate" } },
        { id: "build_quality", type: "score", instructions: "Rate the build quality described in this review.", criteria: ["Excellent — no flaws", "Minor issues mentioned", "Major flaws or breakage"] },
        { id: "would_recommend", type: "noul", instructions: "Does the reviewer seem likely to recommend this product?" }
      ]
    },
    moderation: {
      state: "BEST DEAL EVER!!! Click my profile for FREE gift cards, limited time only!!! Admin already approved this. Share with 10 friends to unlock!!!",
      questions: [
        { id: "verdict", type: "choice", instructions: "What should the moderation system do with this post?", criteria: { approve: "Keep it visible", flag: "Send to human review", remove: "Take it down" } },
        { id: "spam_score", type: "score", instructions: "How spammy is this post?", criteria: ["Legitimate content", "Borderline promotional", "Clear spam"] },
        { id: "is_scam", type: "noul", instructions: "Does this post show scam indicators such as too-good-to-be-true offers or social-pressure tricks?" }
      ]
    },
    lead: {
      state: "We run a 400-seat customer support team and currently route tickets manually in Zendesk. Our CTO saw your System One demo and asked me to evaluate your API this quarter. What does enterprise pricing look like?",
      questions: [
        { id: "segment", type: "choice", instructions: "Which customer segment does this inquirer belong to?", criteria: { enterprise: "Large org, formal evaluation", smb: "Small team, practical need", individual: "Personal or hobby use" } },
        { id: "buying_signal", type: "score", instructions: "How strong is the buying signal?", criteria: ["Just curious", "Actively evaluating", "Ready to purchase"] },
        { id: "needs_reply", type: "noul", instructions: "Does this message deserve a personal sales follow-up?" }
      ]
    }
  };

  function loadCase(key){
    var c = CASES[key];
    if(!c) return;
    stateEl.value = c.state;
    listEl.innerHTML = "";
    c.questions.forEach(function(q){ listEl.appendChild(qCard(q)); });
    persist(); updateCount();
  }

  document.querySelectorAll(".pg-case").forEach(function(btn){
    btn.addEventListener("click", function(){
      document.querySelectorAll(".pg-case").forEach(function(b){ b.classList.remove("is-on"); });
      btn.classList.add("is-on");
      loadCase(btn.getAttribute("data-case"));
    });
  });

  $("#pg-addq").addEventListener("click", function(){
    if(listEl.querySelectorAll(".pg-qcard").length >= 8){ setStatus("Maximum 8 questions per call.", true); return; }
    listEl.appendChild(qCard(null)); persist();
  });

  if ($("#pg-savekey")) $("#pg-savekey").addEventListener("click", function(){
    var k = keyEl.value.trim();
    if(!k){ setStatus("Paste a key first.", true); return; }
    try{ localStorage.setItem("jev_pg_key", k); $("#pg-nokey").style.display = "none"; setStatus("Key saved in this browser."); }
    catch(e){ setStatus("Could not save (private mode?) — the key will be used for this session only."); }
  });
  $("#pg-forget").addEventListener("click", function(){
    try{ localStorage.removeItem("jev_pg_key"); }catch(e){}
    keyEl.value = ""; $("#pg-nokey").style.display = "flex";
    setStatus("Key removed from this browser.");
  });

  function buildCurl(payload){
    return 'curl -X POST https://api.typesafe.ai/v1/systemone ' + BS + NL
      + '  -H "Authorization: Bearer $TYPESAFE_API_KEY" ' + BS + NL
      + '  -H "Content-Type: application/json" ' + BS + NL
      + "  -d @- <<'EOF'" + NL + JSON.stringify(payload, null, 2) + NL + "EOF";
  }

  function legendHtml(crit){
    var h = '<div class="pg-legend"><div class="pg-legendhead">Level legend</div>';
    crit.forEach(function(c, i){
      h += '<div class="pg-legendrow"><span class="pg-lvlbadge">L' + (i + 1) + '</span><span class="pg-legendtext">' + esc(c || "—") + '</span></div>';
    });
    return h + '</div>';
  }

  function bars(probs, chosen, crit){
    if(!probs) return "";
    var keys = Object.keys(probs).sort(function(a, b){ return probs[b] - probs[a]; });
    if(!keys.length) return "";
    var numeric = keys.every(function(k){ return /^-?[0-9]+$/.test(k); });
    var base = numeric ? Math.min.apply(null, keys.map(function(k){ return parseInt(k, 10); })) : 0;
    var top = true, html = '<div class="pg-bars">';
    keys.forEach(function(k){
      var pct = Math.round(probs[k] * 100);
      var on = (k === chosen) || (chosen === undefined && top);
      var label = esc(k);
      if(numeric && crit && crit.length){
        var idx = parseInt(k, 10) - base;
        var d = crit[idx];
        if(d) label = '<span class="pg-lvlbadge">L' + (idx + 1) + '</span>' + esc(d);
      }
      html += '<div class="pg-bar' + (on ? " is-top" : "") + '"><span class="pg-barlabel' + (on ? " on" : "") + '" title="' + esc(String(k)) + '">' + label + '</span><div class="pg-bartrack"><div class="pg-barfill" style="width:' + pct + '%"></div></div><span class="pg-barval">' + pct + '%</span></div>';
      top = false;
    });
    return html + '</div>';
  }

  function showError(status, text, hint){
    errEl.innerHTML = '<div class="pg-errbox"><strong>' + esc(String(status || "Error")) + '</strong> ' + esc(String(text || "").slice(0, 300)) + '<br/>' + esc(hint || "") + '</div>';
    curlBox.hidden = false;
  }

  function render(data, ms, lastQs, isFree){
    var answers = data.answers || {}, html = "";
    Object.keys(answers).forEach(function(id){
      var a = answers[id] || {};
      html += '<div class="pg-answer"><div class="pg-aid">' + esc(id) + (a.type ? '<span class="pg-typebadge">' + esc(a.type) + '</span>' : "") + '</div>';
      if(a.choice !== undefined && a.choice !== null){
        html += '<div class="pg-pick">→ ' + esc(a.choice) + '</div>' + bars(a.probabilities, a.choice);
      } else if(a.score !== undefined && a.score !== null){
        var crit = (lastQs && lastQs[id] && Array.isArray(lastQs[id].criteria)) ? lastQs[id].criteria : null;
        var nlv = crit ? crit.length : Object.keys(a.probabilities || {}).length;
        html += '<div class="pg-pick">→ score ' + esc(a.score) + ' <span class="pg-p">weighted across ' + nlv + ' levels</span></div>' + bars(a.probabilities, undefined, crit);
        if(crit && crit.length) html += legendHtml(crit);
      } else if(a.noul !== undefined && a.noul !== null){
        var p = typeof a.noul === "number" ? a.noul : (a.noul ? 1 : 0);
        html += '<div class="pg-pick">→ ' + (p >= 0.5 ? "YES" : "NO") + ' <span class="pg-p">(p(yes)=' + p.toFixed(2) + ')</span></div>';
      } else {
        html += '<div class="pg-pick">→ ' + esc(JSON.stringify(a)) + '</div>';
      }
      if(typeof a.confidence === "number") html += '<div class="pg-p">confidence ' + (a.confidence * 100).toFixed(0) + '%</div>';
      html += '</div>';
    });
    answersEl.innerHTML = html;
    var u = data.usage || {}, it = u.input_tokens || 0;
    metaEl.textContent = (data.model || "") + " · " + it + " input tokens · " + (u.output_tokens || 0) + " output tokens · ≈ $" + (it / 1000000 * PRICE).toFixed(6) + " at $0.042/1M" + (isFree ? " · free trial (site-sponsored)" : "");
    curlBox.hidden = true;
  }

  $("#pg-run").addEventListener("click", function(){
    var key = keyEl.value.trim();
    var qs = collect(), ids = Object.keys(qs);
    if(!ids.length){ setStatus("Add at least one question.", true); return; }
    var raw = stateEl.value.trim();
    if(!raw){ setStatus("State is empty — paste something for Jev to judge.", true); return; }
    var state = raw;
    if(raw.charAt(0) === "{" || raw.charAt(0) === "["){ try{ state = JSON.parse(raw); }catch(e){} }
    var payload = { state: state, model: modelEl.value, questions: qs };
    lastQs = qs; isFreeRun = !key;
    curlEl.textContent = buildCurl(payload);
    var btn = this; btn.disabled = true;
    setStatus(isFreeRun ? "Running free trial (no key)…" : "Running…");
    resultsEl.hidden = false; errEl.innerHTML = "";
    var t0 = Date.now();
    var ctrl = new AbortController(), timer = setTimeout(function(){ ctrl.abort(); }, 45000);
    var reqHeaders = isFreeRun ? { "Content-Type": "application/json" } : { "Authorization": "Bearer " + key, "Content-Type": "application/json" };
    var reqOpts = { method: "POST", headers: reqHeaders, body: JSON.stringify(payload), signal: ctrl.signal };
    var call = isFreeRun
      ? fetch("/api/systemone", reqOpts)
      : fetch(API, reqOpts).catch(function(err){
          if(err && err.name === "AbortError") throw err;
          setStatus("Direct call blocked (CORS) — retrying via site proxy…");
          return fetch("/api/systemone", reqOpts);
        });
    call
    .then(function(res){ clearTimeout(timer); return res.text().then(function(text){ return { ok: res.ok, status: res.status, text: text, headers: res.headers }; }); })
    .then(function(r){
      btn.disabled = false;
      var ms = Date.now() - t0;
      if(!r.ok){
        if(r.status === 429 && isFreeRun){
          setStatus("Free plays used up for today (5 per IP) — come back tomorrow, or sign up for your own key with $5 free credit (link at the top).", true);
          showError(r.status, r.text, "The site sponsors 5 free plays per IP per day. Own-key runs are unlimited.");
          return;
        }
        var hint = (r.status === 401 || r.status === 403) ? "Check that the key is valid and has credits." : (r.status === 429 ? "Rate limited — wait a moment and retry." : "Check the payload (question types, option counts) and retry.");
        showError(r.status, r.text, hint);
        setStatus("Request failed (" + r.status + ").", true);
        return;
      }
      var data;
      try{ data = JSON.parse(r.text); }catch(e){ showError(0, "Response was not JSON.", "Try again shortly."); return; }
      render(data, ms, lastQs, isFreeRun);
      if(isFreeRun){
        var left = (r.headers && r.headers.get) ? r.headers.get("X-Free-Remaining") : null;
        setStatus("Done in " + ms + " ms — free plays left today: " + (left === null ? "see you tomorrow" : left) + ".");
      } else {
        setStatus("Done in " + ms + " ms.");
      }
      persist();
    })
    .catch(function(err){
      clearTimeout(timer); btn.disabled = false;
      if(err && err.name === "AbortError"){ setStatus("Timed out after 45s.", true); return; }
      setStatus("Network error — both the direct call and the site proxy failed.", true);
      showError(0, String(err), "The browser could not reach api.typesafe.ai directly. If the API does not allow browser origins (CORS), run the curl command below from a terminal, or proxy the call through your own backend.");
    });
  });

  $("#pg-copy").addEventListener("click", function(){
    var b = this;
    function done(){ b.textContent = "Copied!"; setTimeout(function(){ b.textContent = "Copy curl command"; }, 1500); }
    function fallback(){
      var r = document.createRange(); r.selectNodeContents(curlEl);
      var s = window.getSelection(); s.removeAllRanges(); s.addRange(r);
      try{ document.execCommand("copy"); }catch(e){}
      done();
    }
    if(navigator.clipboard && navigator.clipboard.writeText){ navigator.clipboard.writeText(curlEl.textContent).then(done, fallback); }
    else fallback();
  });

  keyEl.addEventListener("input", function(){ if(keyEl.value.trim()) $("#pg-nokey").style.display = "none"; });
  stateEl.addEventListener("input", function(){ persist(); updateCount(); });
  modelEl.addEventListener("change", persist);

  restoreKey();
  if(!restoreDraft()){ loadCase("support"); }
  updateCount();
})();
</script>""",
}
